import { useSession } from "@/src/hooks/useSession";
import { usePlanLifecycle } from "./usePlanLifecycle";
import { useWeeklyEvaluationTrigger } from "./useWeeklyEvaluationTrigger";
import { useQueryClient } from "@tanstack/react-query";
import { useMemo, useCallback } from "react";

export type DashboardStateValue =
  | { type: 'LOADING' }
  | { type: 'NO_ACTIVE_PLAN' }
  | { type: 'EVALUATION_DUE'; duePlanIds: number[] }
  | { type: 'PLAN_FINISHED'; planId: number }
  | { type: 'COMPLETED_TODAY'; task: any }
  | { type: 'PLANNED_DAY'; task: any }
  | { type: 'CATCHUP_DAY'; task: any }
  | { type: 'REST_DAY'; task?: any };

export function useDashboardState(
  type: 'HIFZ' | 'MURAJA',
  plan: any,
  todayTask: any,
  isRestDay: boolean,
  baseLoading: boolean,
  baseRefetch: () => Promise<any>,
  hasTodayLog?: boolean
) {
  const { user } = useSession();
  const queryClient = useQueryClient();
  const { duePlans, duePlanIds, isLoading: loadingEval } = useWeeklyEvaluationTrigger();
  const { getPlanState, isLoading: loadingLifecycle } = usePlanLifecycle();

  const planState = useMemo(() => {
    return getPlanState(plan?.id, type);
  }, [getPlanState, plan?.id, type]);

  const dashboardState = useMemo((): DashboardStateValue => {
    if (baseLoading || loadingEval || loadingLifecycle) {
      return { type: 'LOADING' };
    }

    if (!plan) {
      return { type: 'NO_ACTIVE_PLAN' };
    }

    // 1. Evaluation Day
    const evalDueForType = duePlans.some((p) => p.activityType === type);
    if (planState === "EVALUATION_DUE" || evalDueForType) {
      return {
        type: "EVALUATION_DUE",
        duePlanIds: duePlans
          .filter((p) => p.activityType === type)
          .map((p) => p.localRefId)
          .filter((id): id is number => id != null),
      };
    }

    // 2. Plan Completed
    if (planState === 'COMPLETION_DUE') {
      return { type: 'PLAN_FINISHED', planId: plan.id };
    }

    // 3. Completed Today — user activity always beats Rest Day / Planned Day display
    //    For Muraja: todayTask.status is set when a log exists in DB
    //    For Hifz:  hasTodayLog is derived from hifzDailyLogs in the hook
    const loggedToday =
      (todayTask?.status === 'completed' || todayTask?.status === 'partial') ||
      hasTodayLog === true;

    if (loggedToday && todayTask) {
      return { type: 'COMPLETED_TODAY', task: todayTask };
    }

    // Task evaluation (todayTask is always generated by calculateTodayTask)
    if (todayTask) {
      // 4. Planned Day (not virtual = genuinely scheduled, not yet logged)
      if (!todayTask.isVirtualTask) {
        return { type: 'PLANNED_DAY', task: todayTask };
      }

      // 5. Rest Day with Catch-up
      if (todayTask.isCatchup) {
         return { type: 'CATCHUP_DAY', task: todayTask };
      }
      
      // 6. Rest Day (no catch-up)
      return { type: 'REST_DAY', task: todayTask };
    }

    return { type: 'REST_DAY' };
  }, [plan, planState, todayTask, isRestDay, hasTodayLog, baseLoading, loadingEval, loadingLifecycle, duePlans]);

  const refetchAll = useCallback(async () => {
    if (user?.id) {
      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ['weekly-evaluation-due', user.id] }),
        queryClient.invalidateQueries({ queryKey: ['finished-plans', user.id] }),
      ]);
    }
    await baseRefetch();
  }, [user?.id, baseRefetch, queryClient]);

  return {
    state: dashboardState,
    refetchAll,
    isLoading: baseLoading || loadingEval || loadingLifecycle,
  };
}
